server:
  port: 8090
  
spring.cloud.stream.kafka.binder.brokers: 172.17.0.8:9092

spring.cloud.stream:
  function:
    definition: historyEventConsumer
  bindings:
    historyEventConsumer-in-0:
      destination: history-events